// import '../primes-js/src/test/test.js'
import '../buffer-js/src/test/test.js'
import '../numbers-js/src/test/test.js'
import '../bitcoin-js/src/test/test.js'
import '../hash-js/src/test/test.js'
import '../elliptic-js/src/test/test.js'
import '../finite-field-js/src/test/test.js'
import '../numbers-js/src/test/test.js'
